language: python
dist: xenial
python:
- 3.7

before_install:
- pip install poetry

install:
- poetry install
- poetry --version

script:
# - echo Skipping tests
- poetry run tests
# - poetry run coverage run --source=my_package -m unittest discover -b

before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
- poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false

env:
  global:
  # Command to generate secure variables: travis encrypt VARIABLE=VALUE --add env.global
  # As described in: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
  - secure: Sdi74HcheVEJMU6g2bNDvUyMJfFemusUm85Qmr4vKUejMZGPVvN33u2RsG7qIDDDqA5b4jj+SvvMBGXU+uE7ZQ3+ngbYpG7Cl+2379SVGSHkirSmEQcjo+tIFtZAu9WLVSjztt6+pxr2i6SphhcqXoJ1q5eaCHhhUFCOnNQj1fuYmb550TY306qBkRY7T3scdqPuulaWOScNiun9MrrVoz98tgWlW+MNj7kPGwLddC64MC3UK10Nb9rUNJjMC6hB8p720MFZ8gsObh1oLPNS+ubS+qVa0SY/ceSvmKpuL65JS9Ic8s9A54zaXYxJd3uhAJdFLxwXqZbMMQKkSMlrkmqn946riKAWfPbIOSNn2akcC1uKfvKKH1om3iGg9KCtswfdImYGR02wLXkP635VgZ4Zw0TdG0uOSpE4OEk7wXnzUHkYqvG8J28bSK7BL9LM10ic38HGjFKYKKqvM1W6MbZY4dszKR6a5TE1oOXvnhAwh+u1zuPub3Td9aweAUMs05rDG4c4mt9FGUmGd8Qrm7ZJ2Ax21//kveNwYZuJk2d2IseU3soNXt96n45z/DBg+QiI/jSIRqyVw9Z5Sp8XhCqeRfuMfwmza0JtXWFNnYwF28Dd+DABaITSavcpml4TkAOuvOW+T9x07rcfMnZZhNN0cFEX4WjAefgGK1xdvTg=
  - secure: ZM17TCEfUrbjIrhFcYzzPGQeJe87RpEXC/Q6rTNXKIzWeJuKlOn80+zj5x4HOZbEFrSYB3GMKFfihS8kOhsAbButKWYkXfdm4ean89JYkM4TYwfK9Lo2QxFU54e76rKuWSVFHZR7K19YH3PyRm7JBsEpqizBLbbOtbQk5mWghfkmV3ZrhHyXSKXCI8pkjKjJNLGsSpdSB8spBrBgn85zz/JA8Otfkb5VsNhCfrmeCzbYJUww3og431rPq8SJJ7BlHbY28abWHqzERTNCoiv0v7hn7UyJMQXD+Lj/kFNwJEbHm/R6omVSzjP8tvaKQM0JMpxtj1MP9UwIbZBozrdoQBGYg4oDnUs1pyMqIieWfLZtVcG7m/vNXJPetwfe2QY8jOmrJegl6pHeDqWCpuuEGiyeCm5lPralPfAIrjkGfBnUcm+i+2fEtzbnmJQQdQYiuY68xVU0z3DhxWzMqBXehY0uc4FEznyvGkzRI4m175ygMDeEJr+wZ/kmvUCZTzBLk2DTSSbxGqoiHNy2pjux4GSpvy0U8EgGSYTk0a5j5Z4GlbTqqf0f5FAXphowCVRPPXHCnBMUOOZJcJfU6bbq0/N22N5lK3cxQKRAED5ySy9PvJUO9H7+bpsUomz7mIDTTLU9y4jFe7PjsnBqH/soeSJMYTNZHeryngRqDBEMq9c=
