language: python
dist: xenial
python:
- 3.7

before_install:
- pip install poetry

install:
- poetry install
- poetry --version

script:
# - echo Skipping tests
- poetry run tests
# - poetry run coverage run --source=my_package -m unittest discover -b

before_deploy:
- poetry config http-basic.pypi $PYPI_USER $PYPI_PASS
- poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false

env:
  global:
  # Command to generate secure variables: travis encrypt VARIABLE=VALUE --add env.global
  # As described in: https://docs.travis-ci.com/user/environment-variables/#encrypting-environment-variables
  - secure: ZhdTVLojaja3vrL+0uz85A3RAOJyFb+736V/G1tvjlVqT9h2lLtUQS3CNouHFYnpLypxXRUy7roe7wByydViJRU2e3EULrWOqT5bXNsyzERkp25P9PUZNnHdAnsQYfrvXpHMFDSVfQi/WvpLEsiAWzGnt10cnacmSYM9ke+sz6NMsdrpmyMtsOI47KBaTueqQJbhiMlDGmmm6Gg41Na5PWVza47m6nWoRAuPShujUrwVhHuep036TPu8PKiaekYCekmR0WsD4pmz/Sg6qlc6MexbNdnrB3MidSLFVlgxGcpHZuhu7lyeklhCJioVw3OKzvQkRgMU1xVWMO3ppF4cO/ptqyrRkFJa0YW9J15v9xtqiiN2ruLMGAXQNwD+r6aQ7PpS1Ge/rUkqhGoxDfXoj/TRoFdqrVHjWu4tp3Hcmm8eVKlZ7Bbfoj199z3yQ/O/ElIUXmpNsuH+405yszcVUyg3rs/KnSCSRTFxbnZONEO0csdimnt30wWUBPjR94Pv9F2dDg8B47Yb+8++zteklP9hJ1CPxBit/Nfs6vUkuzvloyKzDYmRnYHAHLpLPFFKEnycTPKGd3lO+8ebUaSqh0S/asszBXTvHVB4JapTvPwN8gjqfRfac+AYUxNdSDgcrCusEljeHBwpdfUQDEwRWBY+AjUxCr2dbZdTFYZm6Lc=
  - secure: CkKPzu1l/kfce+rDfkAi3f+t+t1qZ6vk1XL1wVrI6rh6kfV9qDjFM5QoL0n+e7UJ5WSZ/f81W8+695O0IR9Z5+XI1nKGGSlbZuLtCfkMkZyrPq2MvmbP1Vy0Q2DcBE05rRi9e+NXS7IOC0Ns6Yuj7YEGSspQ8RD/dzYdX0atDx/+jM4wr++cQ43mAYS58MwOxrBEA/0yyx1YJ9OkzCgmCbXdHdRKB8BbI0JhCmhRUzZWHZLxwMJB2exP7tnm9ZRG5zK+qeX5C3Wav9HE7SC5wpueyZX/EHzc1mSRDhIh/X5ov8+dDdMY1d8BERgtf/XQPlfloEPUGZD7AW+92o8ivus9U7gEUmUUcyMRBf4ZhsVSFuYSbKzuR+AC/75v4HZHl1jWF96qt4BJxxiQLJd0d5mUKSNeo09X+EBPXjqJ8utQQgb3nMKRbnTqDf3PAFexXeEfUcxWznoIi0eOZcBPWdnYskTXPJdR56tbh5sS/IMEMF7dTtqkh5mjLcT7iawrUT3conI1F7jGNs5jhX6xf6tVdaVeuWNnPtH5df+vxze1qqAzPxyBHYke3Jlqfbr1nuFVAdypxW2fJkqsfhKS+0JQsT8VlFqJreNaYTV3TMjJ4BfMwWa38vzhmh3BfSkdwUGeHkQF3ZPkgA1NZG0XviK4oGwuPktDyaP8TstQ47w=
